<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove */
$dataPost = json_decode($block->getDeletePostJson(), true);
$id = $dataPost['data']['id'];
?>
<a href="#"
   title="<?= $block->escapeHtmlAttr(__('Remove item')) ?>"
   class="action action-delete"
   data-post='<?= /* @noEscape */ $id ?>'>
    <span>
        <?= $block->escapeHtml(__('Remove item')) ?>
    </span>
</a>
