<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item">
<tr class="item-info">
    <td data-th="<?= $block->escapeHtmlAttr(__('Item')) ?>" class="col item">
        <?php if ($block->hasProductUrl()) :?>
        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
           title="<?= $block->escapeHtmlAttr($block->getProductName()) ?>"
           tabindex="-1"
           class="product-item-photo">
            <?php else :?>
            <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()) :?>
        </a>
    <?php else :?>
        </span>
    <?php endif; ?>
        <div class="product-item-details">
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()) :?>
                    <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                <?php else :?>
                    <?= $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <?php if ($_options = $block->getOptionList()) :?>
                <dl class="item-options">
                    <?php $atributes = $block->getProduct()->getTypeInstance()->getConfigurableAttributes($block->getProduct())->getItems() ?>
                    <?php foreach ($atributes as $key => $atribute) {
                        $_opt[$atribute->getLabel()] = $atribute->getData('options');
                    }?>
                    <?php foreach ($_options as $_option) :?>
                    <b> <?= $block->escapeHtml($_option['label']) ?></b><?=": " . $block->escapeHtml($_option['value']) ?> <br/>
                    <div class="swatch-attribute-options">
                        <div class="swatch-attribute <?= $_option['label'] ?>" attribute-code="<?= $_option['label'] ?>" attribute-id="<?= $_option['option_id'] ?>">
                            <div aria-required="true" class="swatch-attribute-options clearfix">
                                <?php if ($_option['label'] == 'Size')
                                    $optionKey = 'Size';
                                    else $optionKey = 'Color'; ?>
                                <?php foreach ($_opt[$optionKey] as $key => $attr){
                                    if ($optionKey == 'Size'){
                                        if ($_option['value'] == $attr['label']){
                                            $select = 'selected';
                                        }
                                        else $select = '';
                                   ?> <div data-product_id="<?= $product->getId() ?>" class="swatch-option text text-product-<?= $product->getId()?> <?= $select ?>" id="option-label-text-<?= $_option['option_id'] ?>-item-<?= $attr['value_index']?>" data-option_attribute_id="<?= $_option['option_id'] ?>" data-option_inner_text="<?= $attr['label'] ?>"  data-option_id="<?= $attr['value_index']?>"><?=$attr['label']?></div><?php
                                    } else {
                                        $code = $attr['value_index'];
                                        $code = $this->helper(\Perspective\UpdateCart\Helper\Data::class)->getCodeColor($code);
                                            if ($_option['value'] == $attr['label']) $select = 'selected';
                                            else $select = '';
                                        ?>
                                <div data-product_id="<?= $product->getId() ?>" class="swatch-option color color-product-<?= $product->getId()?> <?= $select ?> " id="option-label-color-<?= $_option['option_id'] ?>-item-<?= $attr['value_index']?>" data-option_inner_text="<?= $attr['label'] ?>"
                                     data-option_id="<?= $attr['value_index']?>" style="background: <?= $code ?> no-repeat center; background-size: initial;" data-option_attribute_id="<?= $_option['option_id'] ?>"></div>
                                    <?php }
                                }?>
                            </div>
                            <input class="swatch-input super-attribute-select" id="<?= $_option['option_id'] ?>" value="<?= $_option['option_value'] ?>" name="super_attribute[<?= $_option['option_id'] ?>]" type="text" data-selector="super_attribute[<?= $_option['option_id'] ?>]" style="display: none" aria-required="true" aria-invalid="false" data-attr-name="<?= $_option['option_id'] ?>">
                        </div>
                    </div>
                <?php endforeach; ?>
                </dl>
            <?php endif;?>
            <?php if ($messages = $block->getMessages()) :?>
                <?php foreach ($messages as $message) :?>
                    <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                        <div><?= $block->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock) :?>
                <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif;?>
        </div>
    </td>

    <?php if ($canApplyMsrp) :?>
        <td class="col msrp" data-th="<?= $block->escapeHtmlAttr(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map"
                       id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                       data-mage-init='{"addToCart":{
                                            "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                            "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                            "showAddToCart": false
                                            }
                                        }'
                    >
                        <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                    </a>
                </span>
        </td>
    <?php else :?>
        <td class="col price" data-th="<?= $block->escapeHtmlAttr(__('Price')) ?>">
            <?= $block->getUnitPriceHtml($_item) ?>
        </td>
    <?php endif; ?>
    <td class="col qty" data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>">
        <div class="field qty">
            <div class="control qty">
                <label for="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty">
                    <span class="label"><?= $block->escapeHtml(__('Qty')) ?></span>
                    <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                           name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                           data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                           value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                           type="number"
                           size="4"
                           step="any"
                           title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                           class="input-text qty"
                           data-validate="{required:true,'validate-greater-than-zero':true}"
                           data-role="cart-item-qty"/>
                </label>
            </div>
        </div>
    </td>

    <td class="col subtotal" data-th="<?= $block->escapeHtmlAttr(__('Subtotal')) ?>">
        <?php if ($canApplyMsrp) :?>
            <span class="cart msrp subtotal">--</span>
        <?php else :?>
            <?= $block->getRowTotalHtml($_item) ?>
        <?php endif; ?>
    </td>
</tr>
<tr class="item-actions">
    <td colspan="4">
        <div class="actions-toolbar">
            <?= /* @noEscape */ $block->getActions($_item) ?>
        </div>
    </td>
</tr>
</tbody>
